### ISSUE TITLE
Planning & Tracking of Jinajs & Showcase

### ISSUE THREAD

**Issue by pswu11** [jina-ai/jina-ui#6]
## Showcase

- [x] Create a Monorepo and a blank React project #7
- [x] Set up layout for the page #3 
- [x] Set up boilerplate for the Showcase Sidebar #4 
- [x] Set up boilerplate for the Showcase Flow diagram #5 
- [ ] Add a CI step to test with npm install #8 

## JinaJS (npm package)

- [x] Research and experiment with swagger UI approach #2 
- [x] Set up an npm project for JinaJs #9 
- [x] Create a function that serializes data the JSON to send #10 

## UI Component (a separate npm package)

- [x] #12
- [x] #13
- [x] #11
- [x] #17 (Don't need for now) 

## PDF Showcase

- [x] #20

## Shop-the-look showcase
- [ ] #25

## 3D Model
- [x] #29
